version: '3.9'

services:
  openacs:
    image: "${OACS_REPOSITORY}/${OACS_IMAGE_NAME}:${OACS_IMAGE_TAG}"
    env_file:
      - .env
    volumes:
      - content:/var/www/openacs/content-repository-content-files
      - ./rootfs/usr/local/ns/conf/:/usr/local/ns/conf/
    depends_on:
      - postgres
    ports:
      - ${OACS_LISTEN_PORT}:${oacs_httpport}
    healthcheck:
      test: ["CMD-SHELL", "wget -qO - http://localhost:${oacs_httpport}/SYSTEM/openacs-test || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 2

  postgres:
    image: "${POSTGRES_REPOSITORY}:${POSTGRES_TAG}"
    restart: always
    env_file:
      - .env
    ports:
      - "5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${PGUSER}"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db_data:
  content:
