name: Build and push docker images

on:
  push:
    branches:
      - master
      - main
    paths:
      - '.github/*'
      - '.github/workflows/*'
      - 'src/*.sh'
      - 'src/Dockerfile*'
      - 'src/VERSIONS'
      - 'src/hook/*'
      - 'src/rootfs/*'
      - 'tests/**'
  pull_request:
    branches:
      - master
      - main
    paths:
      - '.github/*'
      - '.github/workflows/*'
      - 'src/*.sh'
      - 'src/Dockerfile*'
      - 'src/VERSIONS'
      - 'src/hook/*'
      - 'src/rootfs/*'
      - 'tests/**'
jobs:
  build:
    name: Build and push image to dockerhub
    runs-on: ubuntu-22.04
    steps:
      - name: Repo checkout
        uses: actions/checkout@v2

      - name: Login to DockerHub Registry
        run: |
          echo  ${{ secrets.DOCKERHUB_TOKEN }} | docker login --username ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: OpenACS. Build and push image.
        run: |
          echo "::group::Prepare environment"
          set -a; source ${GITHUB_WORKSPACE}/src/VERSIONS ; set +a;
          cd ${GITHUB_WORKSPACE}/src/hook
          echo "::endgroup::"
          echo "::group::Build image"
          ./build.sh
          echo "::endgroup::"
          echo "::group::Push image"
          ./push.sh
          echo "::endgroup::"
